### ISSUE TITLE
how to train it on custom dataset

### ISSUE THREAD

**Issue by muhammadhammadjamil** [yjh0410/YOWOv2#27]
@yjh0410 can you provide  guildline how to train YOWOv2 on my own dataset here is alteration i make on dataset config file 
'ava_v2.2': {
        # dataset
        'frames_dir': '/home/ubuntu/Furqan/new_dataset/20231004-activity-all-annotated-tasks/',
        'frame_list': '/home/ubuntu/hammad/YOWOv2/config/frame/',
        'annotation_dir': '/home/ubuntu/hammad/new_annotations/',
        'train_gt_box_list': '/home/ubuntu/hammad/new_annotations/20231005_ke_activity_train_avastyle_17.csv',
        'val_gt_box_list': '/home/ubuntu/hammad/new_annotations/20231005_ke_activity_val_avastyle_17.csv',
        'train_exclusion_file': '/home/ubuntu/hammad/new_annotations/ava_train_excluded_timestamps_v2.2 (1).csv',
        'val_exclusion_file': '/home/ubuntu/hammad/new_annotations/ava_val_excluded_timestamps_v2.2.csv',
        'labelmap_file': '/home/ubuntu/hammad/YOWOv2/labels.pbtxt',  # 'ava_v2.2/ava_action_list_v2.2.pbtxt',
        'class_ratio_file': None,
        'backup_dir': 'results/',
        
        **however it give me this error** 
Model Config: YOWO_V2_LARGE 
Finished loading image paths from: /home/ubuntu/hammad/YOWOv2/config/frame/train.csv
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    train()
  File "train.py", line 156, in train
    dataset, evaluator, num_classes = build_dataset(d_cfg, args, is_train=True)
  File "/home/ubuntu/hammad/YOWOv2/utils/misc.py", line 67, in build_dataset
    dataset = AVA_Dataset(
  File "/home/ubuntu/hammad/YOWOv2/dataset/ava.py", line 49, in __init__
    self._load_data()
  File "/home/ubuntu/hammad/YOWOv2/dataset/ava.py", line 65, in _load_data
    boxes_and_labels = ava_helper.load_boxes_and_labels(
  File "/home/ubuntu/hammad/YOWOv2/dataset/ava_helper.py", line 134, in load_boxes_and_labels
    if box_key not in all_boxes[video_name][frame_sec]:
KeyError: 0

**Comment by xingjinderhuoche** [comment]
can you provide the source dataset ucf24 ？I can not download that. Here is my email 2805211350@qq.com. Thank you.

**Comment by T-wow** [comment]
你好，请问，请问为什么进行DDP训练损失异常的大，但是进行单卡训练没有这种情况。谢谢解答

**Comment by qq3399476669** [comment]
> 你好，请问，请问为什么进行DDP训练损失异常的大，但是进行单卡训练没有这种情况。谢谢解答
你好，请问你的DDP训练的时候，是不是多张卡都有用到，我这里使用的服务器是四张显卡的，但是使用官方提供的ddp命令训练只使用到了一张卡，你有出现这种情况吗
