### ISSUE TITLE
Which torch / torchvision / cuda version should I use for this project?

### ISSUE THREAD

**Issue by SavedowW** [yjh0410/YOWOv2#35]
I have cuda 11.2 on my system, I am trying to run training with this command:
`python train.py --cuda -d ucf24 --root path/to/dataset -v yowo_v2_nano --num_workers 4 --eval_epoch 1 --max_epoch 8 --lr_epoch 2 3 4 5 -lr 0.0001 -ldr 0.5 -bs 8 -accu 16 -K 16`
If I install torch and torchvision using requirements.txt, it runs fine without cuda, but with cuda I get this error:

> AssertionError: Torch not compiled with CUDA enabled

I tried to manually install torch 1.8.0+cu111 and torchvision 0.9.0+cu111, but when I run this command I get this error:

> Traceback (most recent call last):
>   File "train.py", line 330, in <module>
>     train()
>   File "train.py", line 222, in train
>     for iter_i, (frame_ids, video_clips, targets) in enumerate(dataloader):
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
>     return self._get_iterator()
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
>     return _MultiProcessingDataLoaderIter(self)
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
>     w.start()
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\multiprocessing\process.py", line 105, in start
>     self._popen = self._Popen(self)
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\ProgramData\Anaconda3\envs\yowo\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> BrokenPipeError: [Errno 32] Broken pipe

I have no issues with manualy installed cpu only versions of torch and torchvision of the same versions

**Comment by SavedowW** [comment]
Figured it out, python 3.8 with torch 2.0.1, torchvision 0.15.2 and cuda 11.8 works fine

**Comment by SavedowW** [comment]
Figured it out, python 3.8 with torch 2.0.1, torchvision 0.15.2 and cuda 11.8 works fine
